// Major cities by country (ISO 3166-1 alpha-2 codes).
// Only common destinations are seeded with city lists. For other countries,
// the UI shows a free-text input.
//
// Iraq has its own structured taxonomy (governorates) and is intentionally NOT
// included here — the UI shows a Governorate dropdown for IQ instead.

export interface City {
  name: string;       // English
  nameAr: string;     // Arabic transliteration / common Arabic name
}

export const CITIES_BY_COUNTRY: Record<string, City[]> = {
  // -------------------------------------------------------------------- MIDDLE EAST
  AE: [
    { name: 'Abu Dhabi', nameAr: 'أبو ظبي' },
    { name: 'Dubai', nameAr: 'دبي' },
    { name: 'Sharjah', nameAr: 'الشارقة' },
    { name: 'Ajman', nameAr: 'عجمان' },
    { name: 'Ras Al Khaimah', nameAr: 'رأس الخيمة' },
    { name: 'Fujairah', nameAr: 'الفجيرة' },
    { name: 'Umm Al Quwain', nameAr: 'أم القيوين' },
    { name: 'Al Ain', nameAr: 'العين' },
  ],
  SA: [
    { name: 'Riyadh', nameAr: 'الرياض' },
    { name: 'Jeddah', nameAr: 'جدة' },
    { name: 'Mecca', nameAr: 'مكة المكرمة' },
    { name: 'Medina', nameAr: 'المدينة المنورة' },
    { name: 'Dammam', nameAr: 'الدمام' },
    { name: 'Khobar', nameAr: 'الخبر' },
    { name: 'Tabuk', nameAr: 'تبوك' },
    { name: 'Buraidah', nameAr: 'بريدة' },
    { name: 'Khamis Mushait', nameAr: 'خميس مشيط' },
    { name: 'Hail', nameAr: 'حائل' },
    { name: 'Hofuf', nameAr: 'الهفوف' },
    { name: 'Najran', nameAr: 'نجران' },
    { name: 'Yanbu', nameAr: 'ينبع' },
    { name: 'Abha', nameAr: 'أبها' },
    { name: 'Taif', nameAr: 'الطائف' },
    { name: 'Jubail', nameAr: 'الجبيل' },
  ],
  KW: [
    { name: 'Kuwait City', nameAr: 'مدينة الكويت' },
    { name: 'Hawalli', nameAr: 'حولي' },
    { name: 'Salmiya', nameAr: 'السالمية' },
    { name: 'Jahra', nameAr: 'الجهراء' },
    { name: 'Farwaniya', nameAr: 'الفروانية' },
    { name: 'Mubarak Al-Kabeer', nameAr: 'مبارك الكبير' },
    { name: 'Ahmadi', nameAr: 'الأحمدي' },
    { name: 'Fahaheel', nameAr: 'الفحيحيل' },
  ],
  QA: [
    { name: 'Doha', nameAr: 'الدوحة' },
    { name: 'Al Wakrah', nameAr: 'الوكرة' },
    { name: 'Al Khor', nameAr: 'الخور' },
    { name: 'Al Rayyan', nameAr: 'الريان' },
    { name: 'Umm Salal', nameAr: 'أم صلال' },
    { name: 'Al Daayen', nameAr: 'الضعاين' },
    { name: 'Lusail', nameAr: 'لوسيل' },
    { name: 'Mesaieed', nameAr: 'مسيعيد' },
  ],
  BH: [
    { name: 'Manama', nameAr: 'المنامة' },
    { name: 'Riffa', nameAr: 'الرفاع' },
    { name: 'Muharraq', nameAr: 'المحرق' },
    { name: 'Hamad Town', nameAr: 'مدينة حمد' },
    { name: 'Isa Town', nameAr: 'مدينة عيسى' },
    { name: 'Sitra', nameAr: 'سترة' },
  ],
  OM: [
    { name: 'Muscat', nameAr: 'مسقط' },
    { name: 'Salalah', nameAr: 'صلالة' },
    { name: 'Sohar', nameAr: 'صحار' },
    { name: 'Nizwa', nameAr: 'نزوى' },
    { name: 'Sur', nameAr: 'صور' },
    { name: 'Ibri', nameAr: 'عبري' },
    { name: 'Buraimi', nameAr: 'البريمي' },
    { name: 'Rustaq', nameAr: 'الرستاق' },
  ],
  JO: [
    { name: 'Amman', nameAr: 'عمّان' },
    { name: 'Zarqa', nameAr: 'الزرقاء' },
    { name: 'Irbid', nameAr: 'إربد' },
    { name: 'Russeifa', nameAr: 'الرصيفة' },
    { name: 'Aqaba', nameAr: 'العقبة' },
    { name: 'Madaba', nameAr: 'مادبا' },
    { name: 'Salt', nameAr: 'السلط' },
    { name: 'Mafraq', nameAr: 'المفرق' },
    { name: 'Karak', nameAr: 'الكرك' },
    { name: 'Jerash', nameAr: 'جرش' },
  ],
  LB: [
    { name: 'Beirut', nameAr: 'بيروت' },
    { name: 'Tripoli', nameAr: 'طرابلس' },
    { name: 'Sidon', nameAr: 'صيدا' },
    { name: 'Tyre', nameAr: 'صور' },
    { name: 'Zahle', nameAr: 'زحلة' },
    { name: 'Jounieh', nameAr: 'جونية' },
    { name: 'Baalbek', nameAr: 'بعلبك' },
    { name: 'Byblos', nameAr: 'جبيل' },
    { name: 'Nabatieh', nameAr: 'النبطية' },
  ],
  SY: [
    { name: 'Damascus', nameAr: 'دمشق' },
    { name: 'Aleppo', nameAr: 'حلب' },
    { name: 'Homs', nameAr: 'حمص' },
    { name: 'Hama', nameAr: 'حماة' },
    { name: 'Latakia', nameAr: 'اللاذقية' },
    { name: 'Tartus', nameAr: 'طرطوس' },
    { name: 'Deir ez-Zor', nameAr: 'دير الزور' },
    { name: 'Raqqa', nameAr: 'الرقة' },
    { name: 'Daraa', nameAr: 'درعا' },
    { name: 'Sweida', nameAr: 'السويداء' },
    { name: 'Idlib', nameAr: 'إدلب' },
    { name: 'Qamishli', nameAr: 'القامشلي' },
  ],
  EG: [
    { name: 'Cairo', nameAr: 'القاهرة' },
    { name: 'Alexandria', nameAr: 'الإسكندرية' },
    { name: 'Giza', nameAr: 'الجيزة' },
    { name: 'Shubra El Kheima', nameAr: 'شبرا الخيمة' },
    { name: 'Port Said', nameAr: 'بورسعيد' },
    { name: 'Suez', nameAr: 'السويس' },
    { name: 'Mansoura', nameAr: 'المنصورة' },
    { name: 'Tanta', nameAr: 'طنطا' },
    { name: 'Asyut', nameAr: 'أسيوط' },
    { name: 'Ismailia', nameAr: 'الإسماعيلية' },
    { name: 'Faiyum', nameAr: 'الفيوم' },
    { name: 'Zagazig', nameAr: 'الزقازيق' },
    { name: 'Luxor', nameAr: 'الأقصر' },
    { name: 'Aswan', nameAr: 'أسوان' },
    { name: 'Hurghada', nameAr: 'الغردقة' },
    { name: 'Sharm El Sheikh', nameAr: 'شرم الشيخ' },
  ],
  TR: [
    { name: 'Istanbul', nameAr: 'إسطنبول' },
    { name: 'Ankara', nameAr: 'أنقرة' },
    { name: 'Izmir', nameAr: 'إزمير' },
    { name: 'Bursa', nameAr: 'بورصة' },
    { name: 'Adana', nameAr: 'أضنة' },
    { name: 'Gaziantep', nameAr: 'غازي عنتاب' },
    { name: 'Konya', nameAr: 'قونية' },
    { name: 'Antalya', nameAr: 'أنطاليا' },
    { name: 'Diyarbakir', nameAr: 'ديار بكر' },
    { name: 'Mersin', nameAr: 'مرسين' },
    { name: 'Kayseri', nameAr: 'قيصري' },
    { name: 'Eskisehir', nameAr: 'إسكي شهر' },
    { name: 'Trabzon', nameAr: 'طرابزون' },
    { name: 'Şanlıurfa', nameAr: 'شانلي أورفا' },
    { name: 'Mardin', nameAr: 'ماردين' },
  ],
  IR: [
    { name: 'Tehran', nameAr: 'طهران' },
    { name: 'Mashhad', nameAr: 'مشهد' },
    { name: 'Isfahan', nameAr: 'أصفهان' },
    { name: 'Karaj', nameAr: 'كرج' },
    { name: 'Shiraz', nameAr: 'شيراز' },
    { name: 'Tabriz', nameAr: 'تبريز' },
    { name: 'Qom', nameAr: 'قم' },
    { name: 'Ahvaz', nameAr: 'الأهواز' },
    { name: 'Kermanshah', nameAr: 'كرمانشاه' },
    { name: 'Urmia', nameAr: 'أورميا' },
    { name: 'Rasht', nameAr: 'رشت' },
    { name: 'Yazd', nameAr: 'يزد' },
    { name: 'Hamadan', nameAr: 'همدان' },
  ],

  // -------------------------------------------------------------------- WESTERN
  US: [
    { name: 'New York', nameAr: 'نيويورك' },
    { name: 'Los Angeles', nameAr: 'لوس أنجلوس' },
    { name: 'Chicago', nameAr: 'شيكاغو' },
    { name: 'Houston', nameAr: 'هيوستن' },
    { name: 'Phoenix', nameAr: 'فينيكس' },
    { name: 'Philadelphia', nameAr: 'فيلادلفيا' },
    { name: 'San Antonio', nameAr: 'سان أنطونيو' },
    { name: 'San Diego', nameAr: 'سان دييغو' },
    { name: 'Dallas', nameAr: 'دالاس' },
    { name: 'San Francisco', nameAr: 'سان فرانسيسكو' },
    { name: 'Washington, D.C.', nameAr: 'واشنطن العاصمة' },
    { name: 'Boston', nameAr: 'بوسطن' },
    { name: 'Seattle', nameAr: 'سياتل' },
    { name: 'Detroit', nameAr: 'ديترويت' },
    { name: 'Atlanta', nameAr: 'أتلانتا' },
    { name: 'Miami', nameAr: 'ميامي' },
    { name: 'Denver', nameAr: 'دنفر' },
    { name: 'Las Vegas', nameAr: 'لاس فيغاس' },
    { name: 'Minneapolis', nameAr: 'مينيابوليس' },
    { name: 'Portland', nameAr: 'بورتلاند' },
  ],
  GB: [
    { name: 'London', nameAr: 'لندن' },
    { name: 'Birmingham', nameAr: 'برمنغهام' },
    { name: 'Manchester', nameAr: 'مانشستر' },
    { name: 'Glasgow', nameAr: 'غلاسكو' },
    { name: 'Liverpool', nameAr: 'ليفربول' },
    { name: 'Leeds', nameAr: 'ليدز' },
    { name: 'Newcastle upon Tyne', nameAr: 'نيوكاسل' },
    { name: 'Sheffield', nameAr: 'شيفيلد' },
    { name: 'Bristol', nameAr: 'بريستول' },
    { name: 'Edinburgh', nameAr: 'إدنبرة' },
    { name: 'Cardiff', nameAr: 'كارديف' },
    { name: 'Belfast', nameAr: 'بلفاست' },
    { name: 'Nottingham', nameAr: 'نوتنغهام' },
    { name: 'Coventry', nameAr: 'كوفنتري' },
    { name: 'Leicester', nameAr: 'ليستر' },
    { name: 'Oxford', nameAr: 'أكسفورد' },
    { name: 'Cambridge', nameAr: 'كامبريدج' },
  ],
  CA: [
    { name: 'Toronto', nameAr: 'تورنتو' },
    { name: 'Montreal', nameAr: 'مونتريال' },
    { name: 'Vancouver', nameAr: 'فانكوفر' },
    { name: 'Calgary', nameAr: 'كالغاري' },
    { name: 'Ottawa', nameAr: 'أوتاوا' },
    { name: 'Edmonton', nameAr: 'إدمونتون' },
    { name: 'Winnipeg', nameAr: 'وينيبيغ' },
    { name: 'Quebec City', nameAr: 'مدينة كيبيك' },
    { name: 'Halifax', nameAr: 'هاليفاكس' },
    { name: 'Mississauga', nameAr: 'ميسيساوغا' },
    { name: 'Hamilton', nameAr: 'هاميلتون' },
    { name: 'London', nameAr: 'لندن (كندا)' },
  ],
  DE: [
    { name: 'Berlin', nameAr: 'برلين' },
    { name: 'Hamburg', nameAr: 'هامبورغ' },
    { name: 'Munich', nameAr: 'ميونخ' },
    { name: 'Cologne', nameAr: 'كولونيا' },
    { name: 'Frankfurt', nameAr: 'فرانكفورت' },
    { name: 'Stuttgart', nameAr: 'شتوتغارت' },
    { name: 'Düsseldorf', nameAr: 'دوسلدورف' },
    { name: 'Leipzig', nameAr: 'لايبزيغ' },
    { name: 'Dortmund', nameAr: 'دورتموند' },
    { name: 'Essen', nameAr: 'إيسن' },
    { name: 'Bremen', nameAr: 'بريمن' },
    { name: 'Dresden', nameAr: 'درسدن' },
    { name: 'Hannover', nameAr: 'هانوفر' },
    { name: 'Nuremberg', nameAr: 'نورنبرغ' },
  ],
  FR: [
    { name: 'Paris', nameAr: 'باريس' },
    { name: 'Marseille', nameAr: 'مرسيليا' },
    { name: 'Lyon', nameAr: 'ليون' },
    { name: 'Toulouse', nameAr: 'تولوز' },
    { name: 'Nice', nameAr: 'نيس' },
    { name: 'Nantes', nameAr: 'نانت' },
    { name: 'Strasbourg', nameAr: 'ستراسبورغ' },
    { name: 'Montpellier', nameAr: 'مونبلييه' },
    { name: 'Bordeaux', nameAr: 'بوردو' },
    { name: 'Lille', nameAr: 'ليل' },
    { name: 'Rennes', nameAr: 'رين' },
  ],
  SE: [
    { name: 'Stockholm', nameAr: 'ستوكهولم' },
    { name: 'Gothenburg', nameAr: 'غوتنبرغ' },
    { name: 'Malmö', nameAr: 'مالمو' },
    { name: 'Uppsala', nameAr: 'أوبسالا' },
    { name: 'Västerås', nameAr: 'فاستيراس' },
    { name: 'Örebro', nameAr: 'أوربرو' },
    { name: 'Linköping', nameAr: 'لينشوبينغ' },
    { name: 'Helsingborg', nameAr: 'هلسنغبورغ' },
    { name: 'Jönköping', nameAr: 'يونشوبينغ' },
    { name: 'Norrköping', nameAr: 'نورشوبينغ' },
    { name: 'Lund', nameAr: 'لوند' },
    { name: 'Umeå', nameAr: 'أوميا' },
  ],
  NO: [
    { name: 'Oslo', nameAr: 'أوسلو' },
    { name: 'Bergen', nameAr: 'بيرغن' },
    { name: 'Trondheim', nameAr: 'تروندهايم' },
    { name: 'Stavanger', nameAr: 'ستافانغر' },
    { name: 'Drammen', nameAr: 'درامن' },
    { name: 'Fredrikstad', nameAr: 'فريدريكستاد' },
    { name: 'Tromsø', nameAr: 'ترومسو' },
  ],
  DK: [
    { name: 'Copenhagen', nameAr: 'كوبنهاغن' },
    { name: 'Aarhus', nameAr: 'آرهوس' },
    { name: 'Odense', nameAr: 'أودنسه' },
    { name: 'Aalborg', nameAr: 'ألبورغ' },
    { name: 'Esbjerg', nameAr: 'إسبيرغ' },
  ],
  NL: [
    { name: 'Amsterdam', nameAr: 'أمستردام' },
    { name: 'Rotterdam', nameAr: 'روتردام' },
    { name: 'The Hague', nameAr: 'لاهاي' },
    { name: 'Utrecht', nameAr: 'أوتريخت' },
    { name: 'Eindhoven', nameAr: 'آيندهوفن' },
    { name: 'Groningen', nameAr: 'غرونينغن' },
    { name: 'Tilburg', nameAr: 'تيلبورغ' },
    { name: 'Almere', nameAr: 'ألميره' },
  ],
  BE: [
    { name: 'Brussels', nameAr: 'بروكسل' },
    { name: 'Antwerp', nameAr: 'أنتويرب' },
    { name: 'Ghent', nameAr: 'غنت' },
    { name: 'Charleroi', nameAr: 'شارلروا' },
    { name: 'Liège', nameAr: 'لييج' },
    { name: 'Bruges', nameAr: 'بروج' },
  ],
  CH: [
    { name: 'Zurich', nameAr: 'زيورخ' },
    { name: 'Geneva', nameAr: 'جنيف' },
    { name: 'Basel', nameAr: 'بازل' },
    { name: 'Bern', nameAr: 'برن' },
    { name: 'Lausanne', nameAr: 'لوزان' },
    { name: 'Lugano', nameAr: 'لوغانو' },
  ],
  AT: [
    { name: 'Vienna', nameAr: 'فيينا' },
    { name: 'Graz', nameAr: 'غراتس' },
    { name: 'Linz', nameAr: 'لينتس' },
    { name: 'Salzburg', nameAr: 'سالزبورغ' },
    { name: 'Innsbruck', nameAr: 'إنسبروك' },
  ],
  ES: [
    { name: 'Madrid', nameAr: 'مدريد' },
    { name: 'Barcelona', nameAr: 'برشلونة' },
    { name: 'Valencia', nameAr: 'فالنسيا' },
    { name: 'Seville', nameAr: 'إشبيلية' },
    { name: 'Zaragoza', nameAr: 'سرقسطة' },
    { name: 'Málaga', nameAr: 'ملقا' },
    { name: 'Murcia', nameAr: 'مرسية' },
    { name: 'Palma', nameAr: 'بالما' },
    { name: 'Bilbao', nameAr: 'بلباو' },
    { name: 'Granada', nameAr: 'غرناطة' },
  ],
  IT: [
    { name: 'Rome', nameAr: 'روما' },
    { name: 'Milan', nameAr: 'ميلانو' },
    { name: 'Naples', nameAr: 'نابولي' },
    { name: 'Turin', nameAr: 'تورينو' },
    { name: 'Palermo', nameAr: 'باليرمو' },
    { name: 'Genoa', nameAr: 'جنوة' },
    { name: 'Bologna', nameAr: 'بولونيا' },
    { name: 'Florence', nameAr: 'فلورنسا' },
    { name: 'Bari', nameAr: 'باري' },
    { name: 'Venice', nameAr: 'البندقية' },
    { name: 'Verona', nameAr: 'فيرونا' },
  ],
  AU: [
    { name: 'Sydney', nameAr: 'سيدني' },
    { name: 'Melbourne', nameAr: 'ملبورن' },
    { name: 'Brisbane', nameAr: 'بريسبان' },
    { name: 'Perth', nameAr: 'بيرث' },
    { name: 'Adelaide', nameAr: 'أديليد' },
    { name: 'Canberra', nameAr: 'كانبرا' },
    { name: 'Gold Coast', nameAr: 'غولد كوست' },
    { name: 'Newcastle', nameAr: 'نيوكاسل' },
    { name: 'Wollongong', nameAr: 'ولونغونغ' },
    { name: 'Hobart', nameAr: 'هوبارت' },
  ],

  // -------------------------------------------------------------------- ASIA
  CN: [
    { name: 'Beijing', nameAr: 'بكين' },
    { name: 'Shanghai', nameAr: 'شنغهاي' },
    { name: 'Guangzhou', nameAr: 'قوانغتشو' },
    { name: 'Shenzhen', nameAr: 'شنتشن' },
    { name: 'Chengdu', nameAr: 'تشنغدو' },
    { name: 'Hangzhou', nameAr: 'هانغتشو' },
    { name: 'Wuhan', nameAr: 'ووهان' },
    { name: "Xi'an", nameAr: 'شيآن' },
    { name: 'Nanjing', nameAr: 'نانجينغ' },
    { name: 'Tianjin', nameAr: 'تيانجين' },
    { name: 'Chongqing', nameAr: 'تشونغتشينغ' },
  ],
  JP: [
    { name: 'Tokyo', nameAr: 'طوكيو' },
    { name: 'Yokohama', nameAr: 'يوكوهاما' },
    { name: 'Osaka', nameAr: 'أوساكا' },
    { name: 'Nagoya', nameAr: 'ناغويا' },
    { name: 'Sapporo', nameAr: 'سابورو' },
    { name: 'Kobe', nameAr: 'كوبي' },
    { name: 'Kyoto', nameAr: 'كيوتو' },
    { name: 'Fukuoka', nameAr: 'فوكوكا' },
    { name: 'Hiroshima', nameAr: 'هيروشيما' },
  ],
  IN: [
    { name: 'Mumbai', nameAr: 'مومباي' },
    { name: 'Delhi', nameAr: 'دلهي' },
    { name: 'Bangalore', nameAr: 'بنغالور' },
    { name: 'Hyderabad', nameAr: 'حيدر آباد' },
    { name: 'Chennai', nameAr: 'تشيناي' },
    { name: 'Kolkata', nameAr: 'كولكاتا' },
    { name: 'Pune', nameAr: 'بونه' },
    { name: 'Ahmedabad', nameAr: 'أحمد آباد' },
    { name: 'Jaipur', nameAr: 'جايبور' },
    { name: 'Lucknow', nameAr: 'لكناو' },
  ],
  PK: [
    { name: 'Karachi', nameAr: 'كراتشي' },
    { name: 'Lahore', nameAr: 'لاهور' },
    { name: 'Islamabad', nameAr: 'إسلام آباد' },
    { name: 'Faisalabad', nameAr: 'فيصل آباد' },
    { name: 'Rawalpindi', nameAr: 'روالبندي' },
    { name: 'Multan', nameAr: 'مولتان' },
    { name: 'Peshawar', nameAr: 'بيشاور' },
    { name: 'Quetta', nameAr: 'كويتا' },
  ],

  // -------------------------------------------------------------------- AFRICA / OTHER
  MA: [
    { name: 'Casablanca', nameAr: 'الدار البيضاء' },
    { name: 'Rabat', nameAr: 'الرباط' },
    { name: 'Fes', nameAr: 'فاس' },
    { name: 'Marrakesh', nameAr: 'مراكش' },
    { name: 'Tangier', nameAr: 'طنجة' },
    { name: 'Agadir', nameAr: 'أكادير' },
    { name: 'Meknes', nameAr: 'مكناس' },
    { name: 'Oujda', nameAr: 'وجدة' },
  ],
  TN: [
    { name: 'Tunis', nameAr: 'تونس' },
    { name: 'Sfax', nameAr: 'صفاقس' },
    { name: 'Sousse', nameAr: 'سوسة' },
    { name: 'Kairouan', nameAr: 'القيروان' },
    { name: 'Bizerte', nameAr: 'بنزرت' },
    { name: 'Gabès', nameAr: 'قابس' },
  ],
  DZ: [
    { name: 'Algiers', nameAr: 'الجزائر' },
    { name: 'Oran', nameAr: 'وهران' },
    { name: 'Constantine', nameAr: 'قسنطينة' },
    { name: 'Annaba', nameAr: 'عنابة' },
    { name: 'Blida', nameAr: 'البليدة' },
    { name: 'Batna', nameAr: 'باتنة' },
    { name: 'Tlemcen', nameAr: 'تلمسان' },
    { name: 'Setif', nameAr: 'سطيف' },
  ],
  LY: [
    { name: 'Tripoli', nameAr: 'طرابلس' },
    { name: 'Benghazi', nameAr: 'بنغازي' },
    { name: 'Misrata', nameAr: 'مصراتة' },
    { name: 'Zawiya', nameAr: 'الزاوية' },
    { name: 'Sabha', nameAr: 'سبها' },
    { name: 'Tobruk', nameAr: 'طبرق' },
    { name: 'Sirte', nameAr: 'سرت' },
  ],
  SD: [
    { name: 'Khartoum', nameAr: 'الخرطوم' },
    { name: 'Omdurman', nameAr: 'أم درمان' },
    { name: 'Port Sudan', nameAr: 'بورتسودان' },
    { name: 'Kassala', nameAr: 'كسلا' },
    { name: 'Nyala', nameAr: 'نيالا' },
    { name: 'El Obeid', nameAr: 'الأبيض' },
    { name: 'Wad Madani', nameAr: 'ود مدني' },
  ],
  YE: [
    { name: "Sana'a", nameAr: 'صنعاء' },
    { name: 'Aden', nameAr: 'عدن' },
    { name: 'Taiz', nameAr: 'تعز' },
    { name: 'Al Hudaydah', nameAr: 'الحديدة' },
    { name: 'Mukalla', nameAr: 'المكلا' },
    { name: 'Ibb', nameAr: 'إب' },
    { name: 'Hajjah', nameAr: 'حجة' },
    { name: 'Saada', nameAr: 'صعدة' },
  ],
  PS: [
    { name: 'Gaza', nameAr: 'غزة' },
    { name: 'Hebron', nameAr: 'الخليل' },
    { name: 'Nablus', nameAr: 'نابلس' },
    { name: 'Ramallah', nameAr: 'رام الله' },
    { name: 'Bethlehem', nameAr: 'بيت لحم' },
    { name: 'Jericho', nameAr: 'أريحا' },
    { name: 'Jenin', nameAr: 'جنين' },
    { name: 'Tulkarm', nameAr: 'طولكرم' },
    { name: 'Jerusalem', nameAr: 'القدس' },
    { name: 'Khan Yunis', nameAr: 'خان يونس' },
    { name: 'Rafah', nameAr: 'رفح' },
  ],
};

/** Returns the city list for a given country, or empty array if not seeded. */
export function getCitiesForCountry(countryCode: string): City[] {
  return CITIES_BY_COUNTRY[countryCode] || [];
}

/** Returns true if we have a seeded city list for this country. */
export function hasCitiesForCountry(countryCode: string): boolean {
  return countryCode in CITIES_BY_COUNTRY && CITIES_BY_COUNTRY[countryCode].length > 0;
}
