CREATE OR REPLACE FUNCTION public.create_case_with_parties(
  _case jsonb,
  _parties jsonb
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_org_id uuid;
  v_user_id uuid := auth.uid();
  v_case_id uuid;
  v_party jsonb;
  v_has_client boolean := false;
  v_party_type text;
  v_entity_id uuid;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  v_org_id := (_case->>'organization_id')::uuid;
  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'organization_id is required';
  END IF;

  IF NOT public.is_org_staff_member(v_user_id, v_org_id) THEN
    RAISE EXCEPTION 'Access denied: not a staff member of this organization';
  END IF;

  IF _parties IS NULL OR jsonb_array_length(_parties) = 0 THEN
    RAISE EXCEPTION 'A case must have at least one party';
  END IF;

  -- Validate at least one client and entity-client representatives upfront
  FOR v_party IN SELECT * FROM jsonb_array_elements(_parties)
  LOOP
    IF v_party->>'role' = 'client' THEN
      v_has_client := true;
      v_party_type := v_party->>'party_type';
      IF v_party_type = 'entity' THEN
        v_entity_id := (v_party->>'entity_id')::uuid;
        IF v_entity_id IS NULL THEN
          RAISE EXCEPTION 'Entity client requires entity_id';
        END IF;
        IF NOT public.entity_has_active_representative(v_entity_id) THEN
          RAISE EXCEPTION 'Entity client must have at least one active representative';
        END IF;
      END IF;
    END IF;
  END LOOP;

  IF NOT v_has_client THEN
    RAISE EXCEPTION 'A case must have at least one client party';
  END IF;

  -- Insert the case (case_number generated by trigger)
  INSERT INTO public.cases (
    organization_id, case_number, title, title_ar, description, description_ar,
    case_type, status, priority,
    court_name, court_name_ar, court_type, court_case_number,
    judge_name, judge_name_ar,
    filing_date, estimated_value,
    is_visible_to_client, created_by
  )
  VALUES (
    v_org_id,
    COALESCE(_case->>'case_number', 'PENDING'),
    _case->>'title',
    _case->>'title_ar',
    _case->>'description',
    _case->>'description_ar',
    COALESCE(_case->>'case_type', 'civil'),
    COALESCE(_case->>'status', 'intake'),
    COALESCE(_case->>'priority', 'medium'),
    _case->>'court_name',
    _case->>'court_name_ar',
    _case->>'court_type',
    _case->>'court_case_number',
    _case->>'judge_name',
    _case->>'judge_name_ar',
    NULLIF(_case->>'filing_date','')::date,
    NULLIF(_case->>'estimated_value','')::numeric,
    COALESCE((_case->>'is_visible_to_client')::boolean, true),
    COALESCE((_case->>'created_by')::uuid, v_user_id)
  )
  RETURNING id INTO v_case_id;

  -- Insert parties
  FOR v_party IN SELECT * FROM jsonb_array_elements(_parties)
  LOOP
    INSERT INTO public.case_parties (
      organization_id, case_id, party_type, person_id, entity_id, role, is_primary
    )
    VALUES (
      v_org_id,
      v_case_id,
      v_party->>'party_type',
      NULLIF(v_party->>'person_id','')::uuid,
      NULLIF(v_party->>'entity_id','')::uuid,
      v_party->>'role',
      COALESCE((v_party->>'is_primary')::boolean, false)
    );
  END LOOP;

  RETURN v_case_id;
END;
$$;

REVOKE ALL ON FUNCTION public.create_case_with_parties(jsonb, jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_case_with_parties(jsonb, jsonb) TO authenticated;